name: greyfdr
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0 # Or the latest stable version from pub.dev
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.1.2  # To store JWT locally
  jwt_decoder: ^2.0.1 # Decode and validate JWTs
  dio: ^5.9.0
  percent_indicator: ^4.2.5
  flutter_launcher_icons: "^0.14.4" # Use the latest version
  intl: ^0.20.2
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.1


flutter_launcher_icons:
  android: true
  ios: true
  web: true
  windows: true
  image_path: "assets/icon/app_icon.png" # path to your logo

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  
  assets:
    - assets/images/login_bg.png
    - assets/images/onboarding1.jpg
    - assets/images/onboarding2.jpg
    - assets/images/onboarding3.jpg
    - assets/images/splash_bg.jpg
    - assets/images/greyfdr.png
    - assets/images/charity.png
    - assets/images/lifestyle.png
    - assets/images/create.png
    - assets/images/invoices.png
    - assets/icons/personal.png
    - assets/icons/business.png
    - assets/icons/groupb.png
    - assets/icons/charityNP.png
    - assets/images/avatar.png
    - assets/images/iphone.png
    - assets/images/ellipse_29_1.svg
    - assets/images/union_1.svg
    - assets/images/group_139.svg
    - assets/images/httpslottiefilescomanimationssuccessixzuhjaasy.png
    - assets/images/group_6.svg
    - assets/images/group_507_1.svg
    - assets/images/ellipse_50_1.svg
    - assets/images/ellipse_52_1.svg
    - assets/images/ellipse_53_2.svg
    - assets/images/vuesaxboldpeople_1.svg
    - assets/images/ellipse_53_3.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
