name: greyfdr
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.1.2
  jwt_decoder: ^2.0.1
  dio: ^5.9.0
  percent_indicator: ^4.2.5
  intl: ^0.20.2
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.8
  http_parser: ^4.0.0
  mime: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

  web:
    generate: true
    image_path: "assets/icons/app_icon.png"

  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_bg.png
    - assets/images/onboarding1.jpg
    - assets/images/onboarding2.jpg
    - assets/images/onboarding3.jpg
    - assets/images/splash_bg.jpg
    - assets/images/greyfdr.png
    - assets/images/charity.png
    - assets/images/lifestyle.png
    - assets/images/create.png
    - assets/images/personal.png
    - assets/images/invoices.png
    - assets/icons/personal.png
    - assets/icons/business.png
    - assets/icons/groupb.png
    - assets/icons/medical.png
    - assets/icons/education.png
    - assets/icons/travel.png
    - assets/icons/nature.png
    - assets/icons/animal.png
    - assets/icons/social.png
    - assets/icons/disaster.png
    - assets/icons/religion.png
    - assets/icons/business1.png
    - assets/icons/charityNP.png
    - assets/images/avatar.png
    - assets/images/iphone.png
    - assets/images/ellipse_29_1.svg
    - assets/images/union_1.svg
    - assets/images/group_139.svg
    - assets/images/httpslottiefilescomanimationssuccessixzuhjaasy.png
    - assets/images/group_6.svg
    - assets/images/group_507_1.svg
    - assets/images/ellipse_50_1.svg
    - assets/images/ellipse_52_1.svg
    - assets/images/ellipse_53_2.svg
    - assets/images/vuesaxboldpeople_1.svg
    - assets/images/ellipse_53_3.svg
    - assets/icons/
